In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [5]:
df.shape[0]

9704

In [12]:
# How many columns in the dataset have missing values?
mv_count = df.isnull().sum()
mv_count[mv_count > 0]

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

In [17]:
# Max fuel efficiency in Asia
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

In [18]:
# Find the median value of the horsepower column in the dataset.
df['horsepower'].median()

149.0

In [19]:
# Next, calculate the most frequent value of the same horsepower column.
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [20]:
# Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

In [21]:
df['horsepower'].median()

149.0

In [28]:
x = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7).to_numpy()
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [30]:
XTX = x.T.dot(x)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [31]:
# Invert XTX
import numpy as np
xtx_inv = np.linalg.inv(XTX)
xtx_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = (xtx_inv.dot(x.T)) * y
w.sum()

np.float64(0.5187709081074016)